# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "EmbellishForXcode", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end

desc 'Lane run for Appstore'
  lane :appstore do
    match(
      type: 'appstore',
      readonly: false
    )

    build_app(
      scheme: ENV['APP_SCHEME'],
      configuration: 'archive',
      export_method: 'app-store'
    )
	upload_to_app_store
  end

end
